---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: DOCKER_IMAGE_NAME
        ports:
          - containerPort: 5000
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/host
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/host
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "0.4"
            memory: "100Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  backend:
    serviceName: backend-service
    servicePort: 80