---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/azdo-gcp-dev/flask-backend-hostname:10
        ports:
          - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /v1/host
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/host
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            cpu: "0.5"
            memory: "100Mi"
          requests:
            cpu: "0.01"
            memory: "100Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  backend:
    serviceName: backend-service
    servicePort: 80
